spring.application.name=discovery-server
server.port=8761

# Disable self-registration & peer replication for standalone mode
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname:localhost}:${server.port}/eureka/

# Disable wait time when sync empty to speed up boot
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false
eureka.server.peer-node-read-timeout-ms=1000
